id: P006995
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19979
  title: བསྟན་པ་བུ་གཅིག་གི་རྒྱུད་གསེར་གྱི་སྙིང་པོ་ཉི་མ་རབ་ཏུ་སྣང་བྱེད།
  author: ''
  volumes:
    4471137487d74536831be33bdfeb8fe2:
      image_group_id: I2PD19987
      title: Volume 1 of bstan pa bu gcig gi rgyud gser gyi snying po nyi ma rab tu
        snang byed
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
ebook_metadata:
  title: བསྟན་པ་བུ་གཅིག་གི་རྒྱུད་གསེར་གྱི་སྙིང་པོ་ཉི་མ་རབ་ཏུ་སྣང་བྱེད།
  author: ''
  sku: P006995
  cover: cover.jpg
  layers:
  - pagination
