id: P006995
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:34:58.564344
source_metadata:
  id: bdr:W2PD19979
  title: བསྟན་པ་བུ་གཅིག་གི་རྒྱུད་གསེར་གྱི་སྙིང་པོ་ཉི་མ་རབ་ཏུ་སྣང་བྱེད།
  author: ''
  volumes:
    4471137487d74536831be33bdfeb8fe2:
      image_group_id: I2PD19987
      title: Volume 1 of bstan pa bu gcig gi rgyud gser gyi snying po nyi ma rab tu
        snang byed
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
