id: P006995
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19979
  title: བསྟན་པ་བུ་གཅིག་གི་རྒྱུད་གསེར་གྱི་སྙིང་པོ་ཉི་མ་རབ་ཏུ་སྣང་བྱེད།
  author: ''
  volumes:
    ee85f24c98ec442c91b387f63da1548a:
      image_group_id: I2PD19987
      title: ''
      volume_number: 1
      total_pages: 86
ebook_metadata:
  title: བསྟན་པ་བུ་གཅིག་གི་རྒྱུད་གསེར་གྱི་སྙིང་པོ་ཉི་མ་རབ་ཏུ་སྣང་བྱེད།
  author: ''
  sku: P006995
  cover: cover.jpg
  layers:
  - pagination
