id: IB49634C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:32:34+00:00'
last_modified: '2022-06-08T10:54:40.604392+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19979
  title: བསྟན་པ་བུ་གཅིག་གི་རྒྱུད་གསེར་གྱི་སྙིང་པོ་ཉི་མ་རབ་ཏུ་སྣང་བྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DFDD:
      image_group_id: I2PD19987
      title: Volume 1 of bstan pa bu gcig gi rgyud gser gyi snying po nyi ma rab tu
        snang byed
      total_pages: 86
      order: 1
      base_file: DFDD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
